// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	detail_book "github.com/dragranzer/Golang-Mini-Project/features/detail_book"
	mock "github.com/stretchr/testify/mock"
)

// Bussiness is an autogenerated mock type for the Bussiness type
type Bussiness struct {
	mock.Mock
}

// CreateData provides a mock function with given fields: data
func (_m *Bussiness) CreateData(data detail_book.Core) (detail_book.Core, error) {
	ret := _m.Called(data)

	var r0 detail_book.Core
	if rf, ok := ret.Get(0).(func(detail_book.Core) detail_book.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(detail_book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(detail_book.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthorbyBookID provides a mock function with given fields: id
func (_m *Bussiness) GetAuthorbyBookID(id int) []int {
	ret := _m.Called(id)

	var r0 []int
	if rf, ok := ret.Get(0).(func(int) []int); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}
