// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	favorites "github.com/dragranzer/Golang-Mini-Project/features/favorites"
	mock "github.com/stretchr/testify/mock"
)

// Bussiness is an autogenerated mock type for the Bussiness type
type Bussiness struct {
	mock.Mock
}

// CreateData provides a mock function with given fields: data
func (_m *Bussiness) CreateData(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDatabyBookID provides a mock function with given fields: id
func (_m *Bussiness) GetDatabyBookID(id int) (favorites.Core, error) {
	ret := _m.Called(id)

	var r0 favorites.Core
	if rf, ok := ret.Get(0).(func(int) favorites.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(favorites.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDatabyUserID provides a mock function with given fields: id
func (_m *Bussiness) GetDatabyUserID(id int) (favorites.Core, error) {
	ret := _m.Called(id)

	var r0 favorites.Core
	if rf, ok := ret.Get(0).(func(int) favorites.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(favorites.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
