// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	peminjamans "github.com/dragranzer/Golang-Mini-Project/features/peminjamans"
	mock "github.com/stretchr/testify/mock"
)

// Bussiness is an autogenerated mock type for the Bussiness type
type Bussiness struct {
	mock.Mock
}

// CreateData provides a mock function with given fields: data
func (_m *Bussiness) CreateData(data peminjamans.Core) (peminjamans.Core, error) {
	ret := _m.Called(data)

	var r0 peminjamans.Core
	if rf, ok := ret.Get(0).(func(peminjamans.Core) peminjamans.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(peminjamans.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(peminjamans.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllData provides a mock function with given fields:
func (_m *Bussiness) GetAllData() []peminjamans.Core {
	ret := _m.Called()

	var r0 []peminjamans.Core
	if rf, ok := ret.Get(0).(func() []peminjamans.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]peminjamans.Core)
		}
	}

	return r0
}

// GetDetailBookPinjam provides a mock function with given fields: judul
func (_m *Bussiness) GetDetailBookPinjam(judul string) peminjamans.DetailBookPinjam {
	ret := _m.Called(judul)

	var r0 peminjamans.DetailBookPinjam
	if rf, ok := ret.Get(0).(func(string) peminjamans.DetailBookPinjam); ok {
		r0 = rf(judul)
	} else {
		r0 = ret.Get(0).(peminjamans.DetailBookPinjam)
	}

	return r0
}
