// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	books "github.com/dragranzer/Golang-Mini-Project/features/books"
	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// DeleteDatabyBookID provides a mock function with given fields: id
func (_m *Data) DeleteDatabyBookID(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertData provides a mock function with given fields: data
func (_m *Data) InsertData(data books.Core) (books.Core, error) {
	ret := _m.Called(data)

	var r0 books.Core
	if rf, ok := ret.Get(0).(func(books.Core) books.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(books.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(books.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectAllData provides a mock function with given fields:
func (_m *Data) SelectAllData() []books.Core {
	ret := _m.Called()

	var r0 []books.Core
	if rf, ok := ret.Get(0).(func() []books.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]books.Core)
		}
	}

	return r0
}

// SelectData provides a mock function with given fields: name
func (_m *Data) SelectData(name string) ([]books.Core, error) {
	ret := _m.Called(name)

	var r0 []books.Core
	if rf, ok := ret.Get(0).(func(string) []books.Core); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]books.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectbyID provides a mock function with given fields: id
func (_m *Data) SelectbyID(id int) (books.Core, error) {
	ret := _m.Called(id)

	var r0 books.Core
	if rf, ok := ret.Get(0).(func(int) books.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(books.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTersediabyName provides a mock function with given fields: name
func (_m *Data) UpdateTersediabyName(name string) (books.Core, error) {
	ret := _m.Called(name)

	var r0 books.Core
	if rf, ok := ret.Get(0).(func(string) books.Core); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(books.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
