// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	authors "github.com/dragranzer/Golang-Mini-Project/features/authors"
	mock "github.com/stretchr/testify/mock"
)

// Bussiness is an autogenerated mock type for the Bussiness type
type Bussiness struct {
	mock.Mock
}

// CreateData provides a mock function with given fields: data
func (_m *Bussiness) CreateData(data authors.Core) (authors.Core, error) {
	ret := _m.Called(data)

	var r0 authors.Core
	if rf, ok := ret.Get(0).(func(authors.Core) authors.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(authors.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(authors.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllData provides a mock function with given fields:
func (_m *Bussiness) GetAllData() []authors.Core {
	ret := _m.Called()

	var r0 []authors.Core
	if rf, ok := ret.Get(0).(func() []authors.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]authors.Core)
		}
	}

	return r0
}

// GetDetailData provides a mock function with given fields: name
func (_m *Bussiness) GetDetailData(name string) ([]authors.Core, error) {
	ret := _m.Called(name)

	var r0 []authors.Core
	if rf, ok := ret.Get(0).(func(string) []authors.Core); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]authors.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailDatabyID provides a mock function with given fields: id
func (_m *Bussiness) GetDetailDatabyID(id int) (authors.Core, error) {
	ret := _m.Called(id)

	var r0 authors.Core
	if rf, ok := ret.Get(0).(func(int) authors.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(authors.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
